modLoader="javafml"
loaderVersion="[32,)"
license="GNU LGPLv3"
[[mods]]
modId="xpfromharvest"
version="1.2.1"
displayName="XP From Harvest"
displayURL="https://minecraft.curseforge.com/projects/xp-from-harvest"
authors="RealGecko"
description='''
Literally harvest XP
'''
[[dependencies.xpfromharvest]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xpfromharvest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
