modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU LGPLv3"
[[mods]]
modId = "xpfromharvest"
version = "${file.jarVersion}"
displayTest="IGNORE_ALL_VERSION"
displayName = "XP From Harvest"
displayURL = "https://github.com/LiskoSlayer63/XPFromHarvest/tree/1.19"
authors = "LiskoSlayer63"
credits = "RealGecko"
description = '''
Literally harvest XP!

Original mod written by RealGecko, now mostly rewritten by LiskoSlayer63
'''
[[dependencies.xpfromharvest]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.xpfromharvest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
